/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'peo_gfsilva' at '16/12/16 12:41' with Gradle 2.14
 *
 * @author peo_gfsilva, @date 16/12/16 12:41
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
